### ISSUE TITLE
Distributed Training is failing

### ISSUE THREAD

**Issue by santurini** [laekov/fastmoe#156]
I was trying to launch a training with DDP and got this error:
```
TypeError: ensure_nccl(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.distributed.distributed_c10d.ProcessGroupNCCL, arg1: torch.Tensor) -> None

Invoked with: <torch.distributed.distributed_c10d.ProcessGroup object at 0x7fa630e71cb0>, tensor([[ 0.8793,  1.1869, -1.2402,  ...,  0.7247, -0.2372, -0.3371],
```

This is how I setup the training, starting from the distributed process (I use mpirun):
```
rank = int(os.environ["OMPI_COMM_WORLD_RANK"])
local_rank = int(os.environ["OMPI_COMM_WORLD_LOCAL_RANK"])
world_size = int(os.environ["OMPI_COMM_WORLD_SIZE"])

dist.init_distributed(dist_backend="nccl", rank=rank, world_size=world_size)
```

This is how I wrapped the model:
```
model.to(device)
ddp_model = DistributedGroupedDataParallel(model)
```

And the MoE layer is defined like this:
```
self.mlp = FMoETransformerMLP(
            num_expert=2,
            d_model=dim,
            d_hidden=int(dim * mlp_ratio),
            activation=act_layer,
            expert_rank=os.environ.get("OMPI_COMM_WORLD_RANK", 0),
            world_size=2,
            top_k=2,
            gate=gate,
            expert_dp_comm="world"
        )
```

And this is how I update the parameters:
```
loss = loss / num_grad_acc
scaler.scale(loss).backward()
model.allreduce_gradients()

if (i + 1) % num_grad_acc == 0:
    scaler.unscale_(optimizer)
    clip_grad_norm_(model.parameters(), grad_clip)
    scaler.step(optimizer)
    scaler.update()
    scheduler.step()
    optimizer.zero_grad()
```

**Comment by santurini** [comment]
Ok thank you! So the rest of the code is defined correctly?

**Comment by laekov** [comment]
Yes. I suppose this is a separate issue of `ensure_nccl`. You can try if simply calling it produces an error. (It takes a torch comm group and a tensor on CUDA as input)

**Comment by santurini** [comment]
As mentioned here: https://discuss.pytorch.org/t/processgroup-not-converted-to-processgroupnccl/180529/3

Maybe we can just make this small change and then it should work, what do you think?

**Comment by laekov** [comment]
No. We are using a protected member function of `ProcessGroupNCCL`, i.e. `broadcastUniqueNCCLID`, so we cannot do that conversion directly. I am afraid that we need to figure out another way to get the instance of `ProcessGroupNCCL`. 

I am sorry but I am dealing with some really tough staff this week. I will look into this problem later. Maybe you can check the ProcessGroup code of newer PyTorch and see if there is any solution if you are interested.

**Comment by santurini** [comment]
Ok sure no problem, I'll try! Good luck

**Comment by laekov** [comment]
Should be addressed by #157 . Feel free to re-open this thread if there is any further issue.

**Comment by santurini** [comment]
Thank you very much! I'll try it as soon as I can.

**Comment by santurini** [comment]
> Should be addressed by #157 . Feel free to re-open this thread if there is any further issue.

I tried the code with DistributedGroupedDataParallel and it works perfectly fine now but it is extremely slow, I wonder if this is normal or there is a problem with my code.

I paste here for context the model, loaders and update step definition:
```
# build model
train_sampler = DistributedSampler(dataset=train_ds)
train_dl = DataLoader(dataset=train_ds,
                      batch_size=batch_size,
                      sampler=train_sampler,
                      num_workers=cfg.train.data.num_workers
                      )

# build model
model = build_model(...)
model.to(device)
ddp_model = DistributedGroupedDataParallel(model)

# update step (using AMP)
loss = loss / num_grad_acc
scaler.scale(loss).backward()
model.allreduce_gradients()

if (i + 1) % num_grad_acc == 0:
    scaler.step(optimizer)
    scaler.update()
    scheduler.step()
    optimizer.zero_grad()
```
