### ISSUE TITLE
Run into this CUDA error,

### ISSUE THREAD

**Issue by LeoniusChen** [laekov/fastmoe#73]
CUDA error at /home/FMoe_test/fastmoe/cuda/stream_manager.cpp:31 code=101(cudaErrorInvalidDevice) "cudaSetDevice(device)"

Could you help me with this issue? My device info: ubuntu16.04, torch1.8.0, cuda 10.2

**Comment by laekov** [comment]
This error suggests that you try to perform computation on a non-exist GPU. Can you please show the code you are running?

**Comment by LeoniusChen** [comment]
I try to run codes below: 
`
from fmoe.transformer import FMoETransformerMLP

x = torch.rand(64, 64)
model = FMoETransformerMLP()
y = model(x)
`
y=model(x) casue this error

**Comment by laekov** [comment]
This is because you did not move the model and the input to CUDA, while FastMoE only supports computation on CUDA.

The following code should work.

```python
import torch
from fmoe.transformer import FMoETransformerMLP

x = torch.rand(64, 64).cuda()
model = FMoETransformerMLP().cuda()
y = model(x)
```

**Comment by LeoniusChen** [comment]
> This is because you did not move the model and the input to CUDA, while FastMoE only supports computation on CUDA.
> 
> The following code should work.
> 
> ```python
> import torch
> from fmoe.transformer import FMoETransformerMLP
> 
> x = torch.rand(64, 64).cuda()
> model = FMoETransformerMLP().cuda()
> y = model(x)
> ```

Thank you! Problem solved!
